menu:
    Blog: /
    Archive: /archives/
    GitHub: https://github.com/wastemobile
    Rss: /atom.xml

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo:

# Analytics
# google-analytics:
ga: 

# Copyright Infomation
startyear: 2016
